### ISSUE TITLE
resolver_error: Unable to resolve DID document for sphereon:ssi-wallet: invalidDid, 

### ISSUE THREAD

**Issue by arheom** [Sphereon-Opensource/did-siop-auth-web-demo#14]
I am trying to run the demo environment locally (after making the changes from the readme), and started the manual flow. All goes well, and I get a QR code generated, but when I try to use the Sphereon mobile app to scan the code, I am getting the issue:

resolver_error: Unable to resolve DID document for sphereon:ssi-wallet: invalidDid, 

When I do the same with your demo environment https://ssi.sphereon.com/demo/issuer , somehow it works well. And I am trying to understand why it does not work. The mobile app can access the urls.

I also isolated the issue into a postman command:

POST http://IP:5000/sphereon2023/credentials

{"types":["GuestCredential"],"format":"jwt_vc_json","proof":{"proof_type":"jwt","jwt":"eyJ0eXAiOiJvcGVuaWQ0dmNpLXByb29mK2p3dCIsImFsZyI6IkVTMjU2SyIsImtpZCI6ImRpZDpqd2s6ZXlKaGJHY2lPaUpGVXpJMU5rc2lMQ0oxYzJVaU9pSnphV2NpTENKcmRIa2lPaUpGUXlJc0ltTnlkaUk2SW5ObFkzQXlOVFpyTVNJc0luZ2lPaUpqZWxrNVpIa3hibkZpWnpsR1JUVTRhM0JIV2paWFZXaEtSbFZXTW5ORFdUVTRXbFZDWlhSeFJUSlJJaXdpZVNJNklrOUNVR1EwTVZKUVUzbHdjWHB5V2prdFYwdzFkVkpNWVdoT1RtSnNhSFI0TldSWU1scFFSbk5pTkdjaWZRIzAifQ.eyJpYXQiOjE2OTAyNzYzNjUuNDU2LCJleHAiOjE2OTAyNzcwMjUuNDU2LCJhdWQiOiJodHRwOi8vMTAuMC4yLjI6NTAwMC9zcGhlcmVvbjIwMjMiLCJub25jZSI6IjVhMTRjZDdhLTNhYzEtNDQ3OC04YWUzLTEzMzc0MTkwNjFhMCIsImlzcyI6InNwaGVyZW9uOnNzaS13YWxsZXQiLCJqdGkiOiI2OGYwZWEyYS02YWQ4LTQ2MjYtYjAwOC1kZDg0Zjg0YmZmMmUifQ.kqs4HbUlOFwsJEOIRRXmS9Qnva3QLKcb8GuGw4J90QdVySnSmU4ja2Gvdh4Jky5yNN06o0yOy7wp46imAAv3qA"}}

with the result:
{
    "error": "invalid_request",
    "error_description": "resolver_error: Unable to resolve DID document for sphereon:ssi-wallet: invalidDid, "
}

Any idea?

Thanks!

**Comment by nklomp** [comment]
Yes, this has to do with a patch we are applying to the did-jwt library. We still need to create a PR upstream for this.

I think you might not be using pnpm as package manager (notice the extra p in front of the name).
If you are using pnpm then the following patch is automatically applied to fix it locally:

https://github.com/Sphereon-Opensource/OID4VC-demo/blob/develop/patches/did-jwt%406.11.6.patch


So you either would have to patch did-jwt, or use pnpm when installing and building the demo.

Let me now if this doesn't solve the problem for you

**Comment by arheom** [comment]
Yes, it worked, thanks! Was having somehow an old version of pnpm, which did not apply the patches. After updating the version, all worked great!
