### ISSUE TITLE
OID4VP issue

### ISSUE THREAD

**Issue by ssi-dev-90** [Sphereon-Opensource/did-siop-auth-web-demo#95]
Hello. 
I was following the demo instructions and I can issue VC without any issues, but when I try to test the second part OID4VP and I scan the QR to sign in, once i select credential in the wallet, the share button is disabled.

**Comment by ssi-dev-90** [comment]
Update

I can share the credential, after issuing the Sphereon Guest credential here https://ssi.sphereon.com/demo/issuer/
But now when I go on the verifier side
https://ssi.sphereon.com/demo/verifier/
And I select and share the Sphereon Guest credential issued previously, on the wallet it shows (Error: Could not verify auth-status).

**Comment by nklomp** [comment]
Ah, sorry, we really need to update/remove the verifier demo. The Presentation Definition probably is wrong, and I am not sure whether it is actually using the latest SDK. Basically the issuer demo, already does a very similar thing if you choose the wallet flow from the first page. 

Created a ticket that we should resolve it

**Comment by ssi-dev-90** [comment]
I've tried wallet flow from the first page, but there's also some issue. 
Nvm, do you have in some repository up to date agent? Or only this one in this repo?

I'm trying to create a login like this one https://dutchblockchaincoalition.org/en/userlogin , but I am using the agent from this repo and it returns this message 'Supplied presentation_submission was a string instead of JSON. Correctig, but external party should fix their implementation!', and this error 'TypeError: Cannot read properties of undefined (reading 'payload')'

Any idea what's the issue, and how to fix it?
